### ISSUE TITLE
data clues and research usage

### ISSUE THREAD

**Issue by Amarchuk** [nekitmm/starnet#4]
Hello,

I am an astrophysicist from team working with University of Waterloo (UW), Canada. We find this project very interesting and of potential usage for our big ongoing full-sky survey. We would like to experiment with improving `starnet` performance a little (because unfortunately it is not always produce adoptable results) and probably tune it for FITS we will use. Could you share your expertise about data you train on? Specifically:

* Can you share the data used and if yes, on which terms?
* How big the data size for training you use?
* How do you remove stars from images in training data to train the whole net? 

In any case we will surely acknowledge and referencing your work

**Comment by nekitmm** [comment]
Hi!

Thanks for your interest! The training data consists of a few dozens of images with all the stars deleted in PS by hand (there is no other way ensuing high quality of star removal and leaving all other areas of images exactly as they are).

If you want to use it for your particular data, you can clean a few images of your own data and fine-tune existing weights so it works better for your particular star profiles.

Unfortunately, I am not publishing my own training data under any conditions since that's where the huge amount of work went, but I am available to help you as much as I can. Let me know if you are interested and we can discuss things in more details!

**Comment by Amarchuk** [comment]
Thanks @nekitmm for your help! We discuss it within our team (and probably try to prepare our own images) and I will return with more questions if needed.

**Comment by nekitmm** [comment]
Thanks for reaching out, @Amarchuk!

Please do not hesitate to reach out to me with any questions! I am actually very interested in how this will turn out and available for active participation in your project! I am myself in academia and if this will turn into some scientific publication, that would be awesome!

**Comment by Amarchuk** [comment]
Awesome! What are your research interests?

It seems like for now creation of Photoshop-corrected images is the hardest part of preparation (there can be literally hundreds of stars on the image and I don't know yet if it is possible to remove them). How you manage to do that? Any tricks or advices are highly appreciated.

**Comment by nekitmm** [comment]
@Amarchuk, lets take this conversation elsewhere - please drop me an email to mm95 at rice edu!
